.TH BDFTOREP "1" "May 2021" "Uwe Waldmann" "User Commands"
.SH NAME
bdftorep \- generate a symbols file as used by \fIbdf2psf\fR
.SH SYNOPSIS
.B bdftorep
\fIBDFFILE\fR
.SH DESCRIPTION
\fIBdftorep\fR
takes a bdf font file,
generates a symbols file as used by \fIbdf2psf\fR,
and prints it to standard output.
.SH COPYRIGHT
Copyright \(co 2020-2025 Uwe Waldmann.
.PP
Bdftorep may be freely used, copied, or modified
under the terms of the MIT license.
