.TH BDFTOEQUIV "1" "May 2021" "Uwe Waldmann" "User Commands"
.SH NAME
bdftoequiv \- generate an equivalences file as used by \fIbdf2psf\fR
.SH SYNOPSIS
.B bdftoequiv
\fIBDFFILE\fR \fISUBSTITUTIONFILE\fR
.SH DESCRIPTION
\fIBdftoequiv\fR
takes a bdf font file and a substitution file,
generates an equivalences file as used by \fIbdf2psf\fR,
and prints it to standard output.
.SH COPYRIGHT
Copyright \(co 2020-2025 Uwe Waldmann.
.PP
Bdftoequiv may be freely used, copied, or modified
under the terms of the MIT license.
